name: Build & Deploy ASP.NET Core MVC to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Step 4: Build the project
      - name: Build
        run: dotnet build --configuration Release --no-restore

      # Step 5: Publish the project
      - name: Publish
        run: dotnet publish -c Release -o ./publish

      # Step 6: Create appsettings.json using a template approach
      - name: Create appsettings.json
        shell: pwsh
        run: |
          # Create appsettings from a template with placeholder replacement
          $template = @'{
  "ConnectionStrings": { "DefaultConnection": "#SQL_DEFAULT_CONNECTION#" },
  "AzureCommunicationServices": {
    "ConnectionString": "#AZURE_COMM_CONNECTION#",
    "SenderAddress": "#AZURE_COMM_SENDER#"
  },
  "EmailSettings": {
    "RecipientAddress": "#EMAIL_RECIPIENT#",
    "CcAddress": "#EMAIL_CC#",
    "VisitorReportRecipientAddress": "#EMAIL_VISITOR_RECIPIENT#",
    "VisitorReportCcAddress": "#EMAIL_VISITOR_CC#"
  },
  "AzureBlob": {
    "AccountName": "#AZURE_BLOB_ACCOUNT#",
    "AccountKey": "#AZURE_BLOB_KEY#",
    "ContainerName": "#AZURE_BLOB_CONTAINER#"
  },
  "AzureBlobReview": {
    "AccountName": "#AZURE_BLOB_ACCOUNT#",
    "AccountKey": "#AZURE_BLOB_KEY#",
    "ContainerName": "#AZURE_BLOB_REVIEW_CONTAINER#"
  },
  "AzureBlobLogin": {
    "AccountName": "#AZURE_BLOB_ACCOUNT#",
    "AccountKey": "#AZURE_BLOB_KEY#",
    "ContainerName": "#AZURE_BLOB_LOGIN_CONTAINER#"
  }
}
'@
          
          # Replace placeholders with secrets (properly escaped)
          $content = $template
          $content = $content -replace '#SQL_DEFAULT_CONNECTION#', '${{ secrets.SQL_DEFAULT_CONNECTION }}'
          $content = $content -replace '#AZURE_COMM_CONNECTION#', '${{ secrets.AZURE_COMM_CONNECTION }}'
          $content = $content -replace '#AZURE_COMM_SENDER#', '${{ secrets.AZURE_COMM_SENDER }}'
          $content = $content -replace '#EMAIL_RECIPIENT#', '${{ secrets.EMAIL_RECIPIENT }}'
          $content = $content -replace '#EMAIL_CC#', '${{ secrets.EMAIL_CC }}'
          $content = $content -replace '#EMAIL_VISITOR_RECIPIENT#', '${{ secrets.EMAIL_VISITOR_RECIPIENT }}'
          $content = $content -replace '#EMAIL_VISITOR_CC#', '${{ secrets.EMAIL_VISITOR_CC }}'
          $content = $content -replace '#AZURE_BLOB_ACCOUNT#', '${{ secrets.AZURE_BLOB_ACCOUNT }}'
          $content = $content -replace '#AZURE_BLOB_KEY#', '${{ secrets.AZURE_BLOB_KEY }}'
          $content = $content -replace '#AZURE_BLOB_CONTAINER#', '${{ secrets.AZURE_BLOB_CONTAINER }}'
          $content = $content -replace '#AZURE_BLOB_REVIEW_CONTAINER#', '${{ secrets.AZURE_BLOB_REVIEW_CONTAINER }}'
          $content = $content -replace '#AZURE_BLOB_LOGIN_CONTAINER#', '${{ secrets.AZURE_BLOB_LOGIN_CONTAINER }}'
          
          $content | Out-File -FilePath ./publish/appsettings.json -Encoding utf8

      # Step 7: Deploy to Azure Web App
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "my-mvc-app"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
