name: Build & Deploy ASP.NET Core MVC to Azure Linux

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: 'MRAPPTestApplication'
  AZURE_WEBAPP_PACKAGE_PATH: './publish'
  DOTNET_VERSION: '9.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    # Step 3: Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Step 4: Build the project
    - name: Build
      run: dotnet build --configuration Release --no-restore

    # Step 5: Publish the project
    - name: Publish
      run: dotnet publish -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }} --runtime linux-x64

    # Step 6: Create appsettings.json
    - name: Create appsettings.json
      shell: bash
      run: |
        cat > ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/appsettings.json << EOF
        {
          "ConnectionStrings": { 
            "DefaultConnection": "${{ secrets.SQL_DEFAULT_CONNECTION }}"
          },
          "AzureCommunicationServices": {
            "ConnectionString": "${{ secrets.AZURE_COMM_CONNECTION }}",
            "SenderAddress": "${{ secrets.AZURE_COMM_SENDER }}"
          },
          "EmailSettings": {
            "RecipientAddress": "${{ secrets.EMAIL_RECIPIENT }}",
            "CcAddress": "${{ secrets.EMAIL_CC }}",
            "VisitorReportRecipientAddress": "${{ secrets.EMAIL_VISITOR_RECIPIENT }}",
            "VisitorReportCcAddress": "${{ secrets.EMAIL_VISITOR_CC }}"
          },
          "AzureBlob": {
            "AccountName": "${{ secrets.AZURE_BLOB_ACCOUNT }}",
            "AccountKey": "${{ secrets.AZURE_BLOB_KEY }}",
            "ContainerName": "${{ secrets.AZURE_BLOB_CONTAINER }}"
          },
          "AzureBlobReview": {
            "AccountName": "${{ secrets.AZURE_BLOB_ACCOUNT }}",
            "AccountKey": "${{ secrets.AZURE_BLOB_KEY }}",
            "ContainerName": "${{ secrets.AZURE_BLOB_REVIEW_CONTAINER }}"
          },
          "AzureBlobLogin": {
            "AccountName": "${{ secrets.AZURE_BLOB_ACCOUNT }}",
            "AccountKey": "${{ secrets.AZURE_BLOB_KEY }}",
            "ContainerName": "${{ secrets.AZURE_BLOB_LOGIN_CONTAINER }}"
          }
        }
        EOF

    # Step 7: Azure Login
    - name: Login to Azure
      uses: azure/login@v1
      with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}


    # Step 8: Deploy to Azure Web App
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}


