name: Build & Deploy ASP.NET Core MVC to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish -c Release -o ./publish

      - name: Create appsettings.json
        run: |
          echo "{
            \"ConnectionStrings\": { \"DefaultConnection\": \"${{ secrets.SQL_DEFAULT_CONNECTION }}\" },
            \"AzureCommunicationServices\": {
              \"ConnectionString\": \"${{ secrets.AZURE_COMM_CONNECTION }}\",
              \"SenderAddress\": \"${{ secrets.AZURE_COMM_SENDER }}\"
            },
            \"EmailSettings\": {
              \"RecipientAddress\": \"${{ secrets.EMAIL_RECIPIENT }}\",
              \"CcAddress\": \"${{ secrets.EMAIL_CC }}\",
              \"VisitorReportRecipientAddress\": \"${{ secrets.EMAIL_VISITOR_RECIPIENT }}\",
              \"VisitorReportCcAddress\": \"${{ secrets.EMAIL_VISITOR_CC }}\"
            },
            \"AzureBlob\": {
              \"AccountName\": \"${{ secrets.AZURE_BLOB_ACCOUNT }}\",
              \"AccountKey\": \"${{ secrets.AZURE_BLOB_KEY }}\",
              \"ContainerName\": \"${{ secrets.AZURE_BLOB_CONTAINER }}\"
            },
            \"AzureBlobReview\": {
              \"AccountName\": \"${{ secrets.AZURE_BLOB_ACCOUNT }}\",
              \"AccountKey\": \"${{ secrets.AZURE_BLOB_KEY }}\",
              \"ContainerName\": \"${{ secrets.AZURE_BLOB_REVIEW_CONTAINER }}\"
            },
            \"AzureBlobLogin\": {
              \"AccountName\": \"${{ secrets.AZURE_BLOB_ACCOUNT }}\",
              \"AccountKey\": \"${{ secrets.AZURE_BLOB_KEY }}\",
              \"ContainerName\": \"${{ secrets.AZURE_BLOB_LOGIN_CONTAINER }}\"
            }
          }" > ./publish/appsettings.json

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "my-mvc-app"         # replace with your App Service name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
